service:
  name: observer-bot

plugins:
  - serverless-plugin-monorepo
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  stackTags:
    PROJECT: "airmash-leaderboard"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

custom:
  stages:
    - dev
    - prod
    - ci
  gameStatsTableName: airmash-stats-${self:provider.stage}-game-stats

functions:
  eventsConsumer:
    handler: dist/handlers/consumer/handler.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:BatchWriteItem
        Resource: { Fn::GetAtt: [ GameStatsTable, Arn ] }
    timeout: 40
    environment:
      GAME_DATA_URL: https://raw.githubusercontent.com/airmash-refugees/airmash-games/master/games.txt
      GAME_TABLE_NAME: ${self:custom.gameStatsTableName}
    events:
      - eventBridge:
          pattern:
            source:
              - game-bot
            detail-type:
              - login

  endpoint:
    handler: dist/handlers/api/handler.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: { Fn::GetAtt: [ GameStatsTable, Arn ] }
    environment:
      GAME_DATA_URL: https://raw.githubusercontent.com/airmash-refugees/airmash-games/master/games.txt
      GAME_TABLE_NAME: ${self:custom.gameStatsTableName}
      TIMESPAN_IN_DAYS: 7
      MIN_ACCOUNT_LEVEL: 3
      LEADERBOARD_SIZE: 50
    events:
      # TODO Enable caching https://www.serverless.com/plugins/serverless-api-gateway-caching
      - http:
          method: GET
          path: leaderboard
          request:
            parameters:
              paths:
                url: true

resources:
  Resources:
    GameStatsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          - AttributeName: Url
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: Url
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.gameStatsTableName}
