version: 2.1

commands:
  yarn-install-with-cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install YARN dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

executors:
  node-build-environment:
    docker:
      - image: circleci/node:10-browsers
    environment:
      # Forces yarn to preserve colour output (https://github.com/yarnpkg/yarn/issues/5733)
      FORCE_COLOR: true
    working_directory: ~/repo

jobs:
  build-all:
    executor: node-build-environment
    steps:
      - checkout
      - yarn-install-with-cache
      - run:
          name: Build Services
          command: yarn build

  test-unit:
    executor: node-build-environment
    steps:
      - setup_remote_docker
      - checkout
      - yarn-install-with-cache
      - run:
          name: Unit Test
          command: yarn test:unit

  test-integration:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-browsers
        environment:
          FORCE_COLOR: true
      - image: sketchingdev/airbattle-server:4.4.0
        environment:
          SERVER_TYPE: FFA
          SU_PASSWORD: mypass
    steps:
      - setup_remote_docker
      - checkout
      - yarn-install-with-cache
      - run:
          name: Integration Test
          command: yarn test:integration

  deploy-ci:
    working_directory: ~/repo
    executor: node-build-environment
    steps:
      - setup_remote_docker
      - checkout
      - yarn-install-with-cache
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy CI
          command: yarn deploy:ci

workflows:
  version: 2

  commit_jobs:
    jobs:
      - deploy-ci
#      - build-all
#      - test-unit:
#          requires:
#            - flow

#  master:
#    jobs:
#      - build-all:
#          filters:
#            branches:
#              only:
#                master
#      - test-airmash-client:
#          filters:
#            branches:
#              only:
#                master
