import React from 'react';
import './App.css';
import {Divider, Header, Icon, Message} from "semantic-ui-react";
import {Leaderboard} from "./components/Leaderboard";
import {ApiClient} from "./api/ApiClient";

export interface HomeProps {
    client: ApiClient;
}

const Home = ({client}: HomeProps) => {
    return (
        <div>
            {/*<Divider fitted />*/}
            {/*<Message>*/}
            {/*    <Message.Header>How it works</Message.Header>*/}
            {/*    <p>*/}
            {/*        This leaderboard is generated by a bot that periodically logs into all the available games*/}
            {/*        and scrapes the players and their level. If you're not included in the*/}
            {/*        leaderboard then you likely weren't in a game when the bot scraped it.</p>*/}

            {/*    <p>The problem with creating a leaderboard for AIRMASH is that there is no way to discern*/}
            {/*        whether two players with the same name are the same person, since the game allows you*/}
            {/*        to choose any name (regardless of whether someone else might have used it in the past) and the*/}
            {/*        underlying ID assigned to each player isn't maintained across games.*/}
            {/*    </p>*/}
            {/*</Message>*/}
            <Leaderboard client={client}/>
        </div>
    );
}

export default Home;
